name: CI/CD for MedScheduler Frontend

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build the application
        run: npm run build
      - name: Build the Docker image
        run: docker build -t wagnermelo13/medscheduler-frontend:$GITHUB_SHA -f Dockerfile .
      - name: Login to Docker Hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Push the Docker image
        run: docker push wagnermelo13/medscheduler-frontend:$GITHUB_SHA